zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null
  ignore_path: null

source:
  arxiv:
    category: null
    include_cross_list: false
  biorxiv:
    category: ["bioengineering", "bioinformatics", "genomics", "microbiology", "molecular biology", "synthetic biology"]
  medrxiv:
    category: null

email:
  sender: ${oc.env:SMTP_SENDER}
  receiver: ${oc.env:SMTP_RECEIVER}
  smtp_server: ${oc.env:SMTP_SERVER}
  smtp_port: ${oc.decode:${oc.env:SMTP_PORT}}
  smtp_username: ${oc.env:SMTP_USERNAME}
  sender_password: ${oc.env:SMTP_PASSWORD}

llm:
  api:
    key: ${oc.env:LLM_API_KEY}
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
  generation_kwargs:
    model: gemini-3.8-flash
    max_tokens: 65536
  language: English
  rate_limit:
    rpm: 5
    tpm: 250000
    rpd: 20

reranker:
  api:
    key: ${oc.env:EMBEDDING_API_KEY}
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
    model: gemini-embedding-2
    batch_size: 32
  rate_limit:
    rpm: 100
    tpm: 30000
    rpd: 1000

executor:
  debug: ${oc.decode:${oc.env:DEBUG}}
  send_empty: false
  max_paper_num: 100
  source: ["biorxiv"]