name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14.0

      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: Run tests
        run: go test -v -cover ./...
