name: Test (No Email)

on:
  workflow_dispatch:

jobs:
  calculate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run script (no email)
        env:
          CUSTOM_CONFIG: ${{ vars.CUSTOM_CONFIG }}
          NO_EMAIL: "true"
          SAVE_EMAIL_PATH: "email_output.html"
          DEBUG: "true"
        run: |
          if [ -n "$CUSTOM_CONFIG" ]; then
            printf "%b\n" "$CUSTOM_CONFIG" > config/default.yaml
            echo "Use custom config: "
            cat config/default.yaml
          fi
          uv run src/zotero_arxiv_daily/main.py

      - name: Upload email output as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: email-output
          path: email_output.html
          retention-days: 7